services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    restart: unless-stopped

  php:
    build: ./docker/php-fpm
    volumes:
      - ./html:/usr/share/nginx/html
      # - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom.conf
      - ./docker/php-fpm/php-ini:/usr/local/etc/php/conf.d
      - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/docker-php-ext-fpm.ini # Asegúrate de que este montaje exista o ajústalo

    environment:
      DATABASE_HOST: db
      DATABASE_NAME: pruebaTube
      DATABASE_USER: inovajuan
      DATABASE_PASSWORD: inovajuan1234
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234.pass.docker.ejemplo
      MYSQL_DATABASE: pruebaTube
      MYSQL_USER: inovajuan
      MYSQL_PASSWORD: inovajuan1234
    ports:
      - "3306:3306" # Opcional: exponer el puerto para acceso externo
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
